// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://obfsorliqkgqdpwnwoag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9iZnNvcmxpcWtncWRwd253b2FnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg2ODc1MDksImV4cCI6MjA1NDI2MzUwOX0.47PWiU9AydOu8_SPLHAvjryRtjldjpMUfJXHFSwGZ1A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);